// templates/products/page.tsx
import Link from "next/link";
import { polar } from "../../polar";
import type { Product } from "@polar-sh/sdk/models/components";
import { useMemo } from "react";

interface ProductCardProps {
    product: Product
}

export const ProductCard = ({ product }: ProductCardProps) => {
    // Handling just a single price for now
    // Remember to handle multiple prices for products if you support monthly & yearly pricing plans
    const firstPrice = product.prices[0]

    const price = useMemo(() => {
        switch(firstPrice.amountType) {
            case 'fixed':
                // The Polar API returns prices in cents - Convert to dollars for display
                return `$${firstPrice.priceAmount / 100}`
            case 'free':
                return 'Free'
            default:
                return 'Pay what you want'
        }
    }, [firstPrice])

    return (
        <div className="flex flex-col gap-y-24 justify-between p-12 rounded-3xl bg-neutral-950 h-full border border-neutral-900">
            <div className="flex flex-col gap-y-8">
            <h1 className="text-3xl">{product.name}</h1>
            <p className="text-neutral-400">{product.description}</p>
            <ul>
                {product.benefits.map((benefit) => (
                    <li key={benefit.id} className="flex flex-row gap-x-2 items-center">
                        {benefit.description}
                    </li>
                ))}
            </ul>
            </div>
            <div className="flex flex-row gap-x-4 justify-between items-center">
                <Link className="h-8 flex flex-row items-center justify-center rounded-full bg-white text-black font-medium px-4" href={`/checkout?priceId=${firstPrice.id}`}>Buy</Link>
                <span className="text-neutral-500">{price}</span>
            </div>
        </div>
    )
}

export default async function Page() {
  const { result } = await polar.products.list({
    organizationId: process.env.POLAR_ORGANIZATION_ID!,
    isArchived: false // Only fetch products which are published
  })

  return (
    <div className="flex flex-col gap-y-32">
      <h1 className="text-5xl">Products</h1>
      <div className="grid grid-cols-4 gap-12">
        {result.items.map((product) => (
            <ProductCard key={product.id} product={product} />
        ))}
      </div>
    </div>
  );
}

// templates/nuxt/app/pages/products/index.vue
<script setup lang="ts">
import type { Product } from '@polar-sh/sdk/models/components'
import type { ProductPrice } from '@polar-sh/sdk/src/models/components/productprice'

const products = ref<Product[]>([])

// This could be a global store (such a pinia) if your app has one
const fetchPolarProducts = async () => {
  return await useRequestFetch()<Product[]>(`/api/polar/products`)
}

const { data } = await useAsyncData(
    'fetchPolarProducts',
    () => fetchPolarProducts()
)
products.value = data.value ?? []

const formatPrice = (price: ProductPrice) => {
  switch (price.amountType) {
    case 'fixed':
      return `$${price.priceAmount / 100}`
    case 'free':
      return 'Free'
    default:
      return 'Pay what you want'
  }
}
</script>

<template>
  <div class="flex flex-col gap-y-32">
    <h1 class="text-5xl">
      Products
    </h1>
    <div class="grid grid-cols-4 gap-12">
      <div
        v-for="product in products"
        :key="product.id"
        class="flex flex-col gap-y-24 justify-between p-12 rounded-3xl bg-neutral-950 h-full border border-neutral-900"
      >
        <div class="flex flex-col gap-y-8">
          <h1 class="text-3xl">
            {{ product.name }}
          </h1>
          <p class="text-neutral-400">
            {{ product.description }}
          </p>
          <ul>
            <li
              v-for="benefit in product.benefits"
              :key="benefit.id"
              class="flex flex-row gap-x-2 items-center"
            >
              {{ benefit.description }}
            </li>
          </ul>
        </div>
        <div class="flex flex-row gap-x-4 justify-between items-center">
          <NuxtLink
            :to="'/api/checkout?priceId=' + product.prices[0].id"
            external
            class="h-8 flex flex-row items-center justify-center rounded-full bg-white text-black font-medium px-4"
          >
            Buy
          </NuxtLink>
          <span class="text-neutral-500">{{ formatPrice(product.prices[0]) }}</span>
        </div>
      </div>
    </div>
  </div>
</template>
